### ISSUE TITLE
Update to pokeapi v2

### ISSUE THREAD

**Issue by torch2424** [fred-o/node-pokeapi#1]
Hello! I am using your node pokeapi and I love it! I recently found out pokeapiv2 came out, and I was wondering if you were willing to update this to version 2?

I wouldnt mind trying myself, as it seems like a simple find and replace, but if you're interested, let me know and I can fork.

Thank you!

**Comment by torch2424** [comment]
Actually in retrospect, v2 seems to inmplement ALOT of new features, perhaps this will be alot more than a simple find and replace

**Comment by fred-o** [comment]
Hi! I've been waiting for v2 to be available, but hadn't seen it. I'll definitely have a look and see what I can do :)

**Comment by torch2424** [comment]
Rad! Thank you dude! 

To be honest, I'm more of a front end developer, but if I can help at all i'd be happy to!

**Comment by fred-o** [comment]
Yeah, I never got around to that. Sorry, but it looks extremely unlikely that I will work on this in the future.

**Comment by torch2424** [comment]
@fred-o Oh dude I totally feel you on this. I maintain a handful of libraries these days, and I had to do the same thing recently haha! 😂  No worries at all, thanks for updating the issue and things! 😄 And hope you been well all things considered! 🎉
